### PR TITLE
Link documentation about how to debug if the service deployment fails

### PR DESCRIPTION
**Pull request by jadolg**

### CODE REVIEW

**Comment by adebasi** [comment]
Here: https://github.com/Jimdo/discounts-console/runs/4965756922?check_suite_focus=true
I don't see the previous log line `Failed to get deployment for service`. Therefore, I don't expect the new line to show up.

**Comment by jadolg** [comment]
> Here: https://github.com/Jimdo/discounts-console/runs/4965756922?check_suite_focus=true I don't see the previous log line `Failed to get deployment for service`. Therefore, I don't expect the new line to show up.

True, I might need to use a trap here

**Comment by adebasi** [comment]
PTAL: https://github.com/Jimdo/wonderland2-deploy-github-action/pull/13

**Comment by jadolg** [comment]
> PTAL: #13

I think I'd rather use a trap and fail fast for any command in the script. Using this method, if anything fails it'll print this message.

**Review by adebasi — APPROVED** [review]

**Pull request merged**
